service: daily-posts

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-central-1
    iamRoleStatements:
        - Effect: Allow
          Action:
              - secretsmanager:GetSecretValue
          Resource:
              - Fn::Join:
                    - ":"
                    - - arn:aws:secretsmanager
                      - Ref: AWS::Region
                      - Ref: AWS::AccountId
                      - secret:*

functions:
    handlePosts:
        handler: dist/posts.handler
        timeout: 30
        events:
            - http:
                  path: posts
                  method: GET
                  cors: true
    handleRedditPosts:
        handler: dist/reddit-posts.handler
        timeout: 30
        events:
            - http:
                  path: reddit-posts
                  method: GET
                  cors: true
    handleMediumPosts:
        handler: dist/medium-posts.handler
        timeout: 30
        events:
            - http:
                  path: medium-posts
                  method: GET
                  cors: true
package:
    include:
        - dist/**

plugins:
    - serverless-offline
